SELECT DISTINCT 
  RCV.TRANSACTION_DATE RCV_TRX_DATE,
  RCV.CREATION_DATE RCV_CREATION_DATE,
  PO.SEGMENT1 PO,
  PO.AGENT_ID BUYER,
  RCVH.RECEIPT_NUM RCV_NUM,
  RCVH.PACKING_SLIP,
  PO.CREATION_DATE PO_CREATION_DATE,
  VEND.VENDOR_NAME,
  VDET.VENDOR_SITE_CODE,
  POD.LINE_NUM LINE,
  PT.SEGMENT1 ITEM,
  POD.QUANTITY QTY_PO,
  POD.UNIT_MEAS_LOOKUP_CODE PO_UOM,
  POD.UNIT_PRICE PRICE,
  CST.MATERIAL_COST,
  PO.CURRENCY_CODE CURR,
  CASE WHEN RCV.TRANSACTION_TYPE IN ('RETURN TO RECEIVING') THEN (RCV.QUANTITY*-1)
    ELSE RCV.QUANTITY END AS QTY_RCV,
  RCV.UNIT_OF_MEASURE RCV_UOM,
  (POD.UNIT_PRICE*(CASE WHEN RCV.TRANSACTION_TYPE IN ('RETURN TO RECEIVING') THEN (RCV.QUANTITY*-1)
    ELSE RCV.QUANTITY END)) AS AMOUNT,
  INV.INVOICE_DATE,
  IVD.CREATION_DATE INV_CREATION_DATE,
  INV.DOC_SEQUENCE_VALUE JV_NO,
  INV.INVOICE_NUM,
  CASE WHEN INV.CANCELLED_AMOUNT IS NOT NULL THEN 'CANCELLED'

    ELSE CASE WHEN AP.REVERSAL_FLAG = 'Y' THEN 'REVERSED' 
    ELSE CASE WHEN RCV.TRANSACTION_TYPE = 'RETURN TO RECEIVING' THEN 'RETURN'
    ELSE CASE WHEN (SELECT COUNT(RCVT.SHIPMENT_LINE_ID) FROM APPS.MEW_C_RCV_SHIPMENT_HEADER_ID_V RCVSH, APPS.MEW_C_RCV_TRANSACTIONS_ID_V RCVT 
      WHERE RCVT.SHIPMENT_HEADER_ID = RCVSH.SHIPMENT_HEADER_ID 
      AND RCVSH.RECEIPT_NUM = RCVH.RECEIPT_NUM 
      AND RCVT.SHIPMENT_LINE_ID = RCV.SHIPMENT_LINE_ID
      AND RCVSH.SHIP_TO_ORG_ID=222 and RCVT.ORGANIZATION_ID='222' 
      AND RCVT.TRANSACTION_TYPE IN ('RETURN TO RECEIVING')) >= 1 THEN 'RETURN' END
    END END END AS INV_STATUS,  AP.POSTED_FLAG
FROM (SELECT * FROM APPS.MEW_C_RCV_TRANSACTIONS_ID_V WHERE ORGANIZATION_ID='222' AND TRANSACTION_DATE BETWEEN '01-Jul-2017' AND '30-Aug-2017'
    AND TRANSACTION_TYPE IN ('RECEIVE', 'RETURN TO RECEIVING')) RCV
    LEFT OUTER JOIN (SELECT * FROM APPS.MEW_C_AP_INVOICE_LINES_ID_V WHERE MATCH_TYPE = 'ITEM_TO_RECEIPT') IVD 
    ON IVD.RCV_TRANSACTION_ID = RCV.TRANSACTION_ID
    LEFT OUTER JOIN APPS.MEW_C_AP_INVOICES_ALL_ID_V INV ON INV.INVOICE_ID = IVD.INVOICE_ID 
    LEFT OUTER JOIN APPS.MEW_C_RCV_SHIPMENT_HEADER_ID_V RCVH ON RCV.SHIPMENT_HEADER_ID = RCVH.SHIPMENT_HEADER_ID
    LEFT OUTER JOIN APPS.MEW_C_PO_HEADERS_ALL_ID_V PO ON RCV.ORGANIZATION_ID = PO.ORG_ID AND RCV.PO_HEADER_ID = PO.PO_HEADER_ID
    LEFT OUTER JOIN APPS.MEW_C_PO_LINES_ARC_ALL_ID_V POD ON PO.PO_HEADER_ID = POD.PO_HEADER_ID AND RCV.PO_LINE_ID = POD.PO_LINE_ID
    LEFT OUTER JOIN APPS.MEW_C_MTL_SYSTEM_ITEMS_B_ID_V PT ON POD.ORG_ID = PT.ORGANIZATION_ID AND POD.ITEM_ID = PT.INVENTORY_ITEM_ID
    LEFT OUTER JOIN APPS.MEW_C_CST_ITEM_COSTS_ID_V CST ON CST.INVENTORY_ITEM_ID = PT.INVENTORY_ITEM_ID AND CST.ORGANIZATION_ID=222 AND CST.COST_TYPE_ID=3
    LEFT OUTER JOIN APPS.MEW_C_AP_SUPPLIERS_ID_V VEND ON RCV.VENDOR_ID = VEND.VENDOR_ID
    LEFT OUTER JOIN APPS.MEW_C_AP_SUPPLIER_SITES_ID_V VDET ON RCV.VENDOR_SITE_ID = VDET.VENDOR_SITE_ID
    LEFT OUTER JOIN APPS.MEW_C_AP_INVOICE_DISTRIB_ID_V AP ON IVD.INVOICE_ID = AP.INVOICE_ID 
    AND IVD.LINE_NUMBER = AP.INVOICE_LINE_NUMBER AND RCV.TRANSACTION_ID = AP.RCV_TRANSACTION_ID AND AP.LINE_TYPE_LOOKUP_CODE='ACCRUAL'
WHERE POD.LATEST_EXTERNAL_FLAG = 'Y'
ORDER BY PO.SEGMENT1, POD.LINE_NUM, RCVH.RECEIPT_NUM, IVD.CREATION_DATE ASC