SELECT  CASE WHEN ARD.SALES_ORDER IS NULL THEN 'MANUAL'
          ELSE 'IMPORT' END AS SOURCE,
        AR.TRX_NUMBER AR_NO,
        AR.ATTRIBUTE10 INVOICE_NO,
        AR.CT_REFERENCE DELIVERY_NO,
        ARD.SALES_ORDER,
        OM.CUST_PO_NUMBER,
        CUST.ACCOUNT_NUMBER BILL_TO,
        BILL_PARTY.PARTY_NAME BILL_CUSTOMER,
        --ar.BILL_TO_CUSTOMER_ID BILL_TO,
        CASE WHEN AR.SHIP_TO_CUSTOMER_ID IS NULL THEN ''
          ELSE (SELECT HZ_LOC.ADDRESS1 FROM APPS.MEW_C_HZ_CUST_SITE_USES_ID_V SITE, APPS.MEW_C_HZ_CUST_ACCT_SITES_ID_V LOC,
          APPS.MEW_C_HZ_PARTY_SITES_ID_V HZ_PARTY, APPS.MEW_C_HZ_LOCATIONS_ID_V HZ_LOC
          WHERE AR.SHIP_TO_SITE_USE_ID = SITE.SITE_USE_ID AND LOC.CUST_ACCT_SITE_ID = SITE.CUST_ACCT_SITE_ID
          AND LOC.PARTY_SITE_ID = HZ_PARTY.PARTY_SITE_ID AND HZ_PARTY.LOCATION_ID = HZ_LOC.LOCATION_ID) END AS SHIP_TO,
        AR.CREATION_DATE,
        NDLV.ATTRIBUTE4 INV_DATE,
        AR.INVOICE_CURRENCY_CODE CURRENCY, 
        AR.EXCHANGE_RATE,
        ARD.LINE_NUMBER LINE,
        PT.SEGMENT1 ITEM_NUMBER,
        case when PT.SEGMENT1 IS NULL THEN ''
          else (select MTL_CAT.SEGMENT2 
          from APPS.MEW_C_MTL_ITEM_CATEGORIES_ID_V ITEM_CAT, APPS.MEW_C_MTL_CATEGORIES_ID_V MTL_CAT 
          where PT.INVENTORY_ITEM_ID = ITEM_CAT.INVENTORY_ITEM_ID and ITEM_CAT.CATEGORY_ID = MTL_CAT.CATEGORY_ID 
          and PT.ORGANIZATION_ID='222' and ITEM_CAT.ORGANIZATION_ID='222' and MTL_CAT.SEGMENT1='26') end as COST_CENTER,
        case when PT.SEGMENT1 is null then ''
          else (select MTL_CAT.SEGMENT3 
          from APPS.MEW_C_MTL_ITEM_CATEGORIES_ID_V ITEM_CAT, APPS.MEW_C_MTL_CATEGORIES_ID_V MTL_CAT 
          where PT.INVENTORY_ITEM_ID = ITEM_CAT.INVENTORY_ITEM_ID and ITEM_CAT.CATEGORY_ID = MTL_CAT.CATEGORY_ID 
          and PT.ORGANIZATION_ID='222' and ITEM_CAT.ORGANIZATION_ID='222' and MTL_CAT.SEGMENT1='26') end as ITEM_TYPE,  
        ARD.QUANTITY_INVOICED QTY,
        ARD.UNIT_SELLING_PRICE PRICE,
        ARD.LINE_RECOVERABLE AMOUNT,
        ARD.TAX_RECOVERABLE TAX
        
FROM  APPS.MEW_C_RA_CUST_TRX_ALL_ID_V AR LEFT JOIN APPS.MEW_C_HZ_CUST_ACCOUNTS_ID_V CUST
      ON AR.BILL_TO_CUSTOMER_ID = CUST.CUST_ACCOUNT_ID LEFT JOIN APPS.MEW_C_HZ_PARTIES_ID_V BILL_PARTY
      ON BILL_PARTY.PARTY_ID    = CUST.PARTY_ID LEFT JOIN APPS.MEW_C_WSH_NEW_DELIVERIES_ID_V NDLV 
      ON AR.CT_REFERENCE = TO_CHAR(NDLV.DELIVERY_ID) LEFT JOIN APPS.MEW_C_RA_CUST_TRX_LINES_ID_V ARD 
      ON AR.CUSTOMER_TRX_ID = ARD.CUSTOMER_TRX_ID LEFT JOIN  APPS.MEW_C_OE_ORDER_HEADERS_ID_V OM
      ON ARD.SALES_ORDER = OM.ORDER_NUMBER LEFT JOIN APPS.MEW_C_MTL_SYSTEM_ITEMS_B_ID_V PT
      ON ARD.INVENTORY_ITEM_ID = PT.INVENTORY_ITEM_ID AND PT.ORGANIZATION_ID='222'
WHERE 
AR.CREATION_DATE  >='01-Mar-2017' 
and ARD.SALES_ORDER IS NOT NULL
AND AR.ATTRIBUTE_CATEGORY='222'  
AND ARD.LINE_TYPE='LINE' 
ORDER BY BILL_PARTY.PARTY_NAME, AR.CREATION_DATE, AR.TRX_NUMBER, ARD.LINE_NUMBER ASC
